<a href="https://colab.research.google.com/github/Suraj9989/Python-problem-Analytics-/blob/main/Libraries_NumPy_%26_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the
dataset information to understand its structure.

In [ ]:
import pandas as pd
df = pd.read_csv("/content/retail_dataset .csv")
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

In [ ]:
df.describe()

        Quantity        Price
count  98.000000    95.000000
mean    5.959184   820.526316
std     2.871540   611.170030
min     1.000000    92.000000
25%     3.250000   426.000000
50%     6.500000   669.000000
75%     8.000000   985.000000
max    10.000000  2901.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

In [ ]:
df.isna().sum()

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

In [ ]:
print(df.isna().sum())
print(df.isna().count())

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64
Transaction ID      100
Customer ID         100
Product Category    100
Quantity            100
Price               100
Date                100
Region              100
dtype: int64

In [ ]:
null_values = df.isnull()
null_values

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False

In [ ]:
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].mean())
df["Price"] = df["Price"].fillna(df["Price"].mean())

In [ ]:
print(df['Quantity'].isnull().sum())
print(df['Price'].isnull().sum())

0
0

 Remove all rows where the Product Category or Region column contains missing values

In [ ]:
df.dropna(subset=['Product Category', 'Region'], inplace=True)
print(df[['Product Category', 'Region']].isnull().sum())

Product Category    0
Region              0
dtype: int64